version: '3.7'

networks:
  fonos:
  host_mode:
    external:
      name: 'host'

volumes:
  apps:
    external: true
  recordings:
    external: true
  datasource:
    external: true
  datasource_auth:
    external: true
  data1-1:
    external: true
