# The following set of services is used to create and install access keys. 
# When running on K8s this function is replaced with the command `fonos config:init`

version: '3.7'

networks:
  fonos:

volumes:
  apps:
    external: true
  datasource:

secrets:
  jwt-salt:
    external: true
  config:
    external: true

configs:
  fluent:
    external: true
  bootstrap:
    external: true
  redis-conf:
    external: true