# The following set of services is used to create and install access keys. 
# When running on K8s this function is replaced with the command `fonos config:init`

version: '3.7'

services:
  access-config:
    image: fonoster/jwthelper
    deploy:
      restart_policy: 
        condition: none
    environment:
      ISS: ${APISERVER_ACCESS_KEY_ISS}
      ACCESS_KEY_ID: ${APISERVER_ACCESS_KEY_ID}
      PRINT_ACCESS_INFO: 'true'
    volumes:
      - config:/home/fonos/access
volumes:
  data1-1: {}
  datasource: {}
  config: {}
networks:
  fonos: {}
