version: '3.7'

services:

  auth:
    image: fonoster/fonos-auth
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.auth_api.rule=PathPrefix(`/fonos.auth.v1alpha1`)"
      - "traefik.http.services.auth_api.loadbalancer.server.scheme=h2c"
    volumes:
      - ${CONFIG}/rbac.json:/home/fonos/rbac.json

  agents:
    image: fonoster/fonos-agents
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.agents_api.rule=PathPrefix(`/fonos.agents.v1alpha1`)"
      - "traefik.http.services.agents_api.loadbalancer.server.scheme=h2c"
  
  domains:
    image: fonoster/fonos-domains
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.domains_api.rule=PathPrefix(`/fonos.domains.v1alpha1`)"
      - "traefik.http.services.domains_api.loadbalancer.server.scheme=h2c"
  
  numbers:
    image: fonoster/fonos-numbers
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.numbers_api.rule=PathPrefix(`/fonos.numbers.v1alpha1`)"
      - "traefik.http.services.numbers_api.loadbalancer.server.scheme=h2c"

  providers:
    image: fonoster/fonos-providers
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.providers_api.rule=PathPrefix(`/fonos.providers.v1alpha1`)"
      - "traefik.http.services.providers_api.loadbalancer.server.scheme=h2c"

  storage:
    image: fonoster/fonos-storage
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.storage_api.rule=PathPrefix(`/fonos.storage.v1alpha1`)"
      - "traefik.http.services.storage_api.loadbalancer.server.scheme=h2c"
  
  callmanager:
    image: fonoster/fonos-callmanager
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.callmanager_api.rule=PathPrefix(`/fonos.callmanager.v1alpha1`)"
      - "traefik.http.services.callmanager_api.loadbalancer.server.scheme=h2c"

  appmanager:
    image: fonoster/fonos-appmanager
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.http.routers.appmanager_api.rule=PathPrefix(`/fonos.appmanager.v1alpha1`)"
      - "traefik.http.services.appmanager_api.loadbalancer.server.scheme=h2c"