version: '3.7'

services:

  storage:
    image: fonoster/fonos-storage
    restart: ${RESTART_POLICY}
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      ALLOW_INSECURE: ${APISERVER_ALLOW_INSECURE}
      # Warning: Temporal variable
      FS_HOST: ${FS_HOST_PUBLIC}
      FS_PORT: ${FS_PORT}
      FS_USERNAME: ${FS_USERNAME}
      FS_SECRET: ${FS_SECRET}
      FS_DEFAULT_STORAGE_BUCKET: ${FS_DEFAULT_STORAGE_BUCKET}
      LOG_OPT_TAG_PREFIX: ${LOG_OPT_TAG_PREFIX}
      LOGS_DRIVER_HOST: ${LOGS_DRIVER_HOST}
      LOGS_DRIVER_PORT: ${LOGS_DRIVER_PORT}
    labels:
      - "traefik.http.routers.apiserver.rule=PathPrefix(`/fonos.storage.v1alpha1`)"
      - "traefik.http.services.apiserver.loadbalancer.server.scheme=h2c"
    # ports:
    #  - 50052:50052   
    networks:
      fonos:
    volumes:
      - ${CONFIG}/certs/ca-key.pem:/home/fonos/.fonos/jwt.salt
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.storage
