# The following services are mandatories for a Fonos deployment

services:

  apiserver:
    extends:
      file: common.yml
      service: common 
    image: ${AS_IMAGE}
    environment:
      ALLOW_INSECURE: 'true'
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
      FS_HOST: ${FS_HOST}
      FS_PORT: ${FS_PORT}
      FS_USERNAME: ${FS_USERNAME}
      FS_SECRET: ${FS_SECRET}
      FS_DEFAULT_STORAGE_BUCKET: ${FS_DEFAULT_STORAGE_BUCKET}
      EVENTS_BROKERS: amqp://${EB_USERNAME}:${EB_SECRET}@${EB_HOST}:${EB_PORT}
      SIPPROXY_HOST: ${SIPPROXY_HOST}
      SIPPROXY_API_PORT: ${SIPPROXY_API_PORT}
      SIPPROXY_API_USERNAME: ${SIPPROXY_API_USERNAME}
      SIPPROXY_API_SECRET: ${SIPPROXY_API_SECRET}
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    deploy:
      placement:
        constraints:
          - node.labels.topic == api  
    networks:
      fonos:
        aliases:
          - ${APISERVER_ENDPOINT}

  datasource:
    extends:
      file: common.yml
      service: common 
    image: ${DS_IMAGE}
    command: ['redis-server', '--appendonly', 'yes' ]
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource
    ports:
      # Not recommended in production environments
      - ${DS_PORT}:${DS_PORT}
    deploy:
      placement:
        constraints:
          - node.labels.topic == api   
    networks:
      fonos:
        aliases: 
          - ${DS_HOST}
    volumes: 
      - datasource:/data

  eventsbroker:
    extends:
      file: common.yml
      service: common 
    image: ${EB_IMAGE}
    environment:
      RABBITMQ_USERNAME: ${EB_USERNAME}
      RABBITMQ_PASSWORD: ${EB_SECRET}
      RABBITMQ_NODE_PORT_NUMBER: ${EB_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.eventsbroker
    ports:
      # Not recommended in production environments
      - ${EB_PORT}:${EB_PORT}
    deploy:
      placement:
        constraints:
          - node.labels.topic == api
    networks:
      fonos:
        aliases: 
          - ${EB_HOST}

  fs:
    extends:
      file: common.yml
      service: common    
    image: ${FS_IMAGE}
    volumes:
      - data1-1:/fonos
    environment:
      MINIO_ACCESS_KEY: ${FS_USERNAME}
      MINIO_SECRET_KEY: ${FS_SECRET}
    command: minio server /fonos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.fs
    ports:
      # Not recommended in production environments
      - ${FS_PORT}:${FS_PORT}
    deploy:
      placement:
        constraints:
          - node.labels.topic == api
    networks:
      fonos:
        aliases: 
          - ${FS_HOST}

  createbuckets:
    image: minio/mc
    deploy:
      restart_policy: 
        condition: on-failure    
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add fs http://${FS_HOST}:${FS_PORT} ${FS_USERNAME} ${FS_SECRET};
      /usr/bin/mc mb fs/apps;
      /usr/bin/mc mb fs/default;
      /usr/bin/mc mb fs/recordings;
      /usr/bin/mc policy set public fs/default;
      /usr/bin/mc policy set public fs/recordings;
      exit 0;
      "
    networks:
      fonos:  