# The following services are mandatories for a Fonos deployment

services:

  apiserver:
    extends:
      file: common.yml
      service: common
    image: ${AS_IMAGE}
    environment:
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
      # Warning: Temporal variable
      FS_HOST: ${FS_HOST_PUBLIC}
      FS_PORT: ${FS_PORT}
      FS_USERNAME: ${FS_USERNAME}
      FS_SECRET: ${FS_SECRET}
      FS_DEFAULT_STORAGE_BUCKET: ${FS_DEFAULT_STORAGE_BUCKET}
      EVENTS_BROKERS: amqp://${EB_USERNAME}:${EB_SECRET}@${EB_HOST}:${EB_PORT}
      SIPPROXY_HOST: ${SIPPROXY_HOST}
      SIPPROXY_API_PORT: ${SIPPROXY_API_PORT}
      SIPPROXY_API_USERNAME: ${SIPPROXY_API_USERNAME}
      SIPPROXY_API_SECRET: ${SIPPROXY_API_SECRET}
      LOGS_DRIVER_HOST: ${LOGS_DRIVER_HOST}
      LOGS_DRIVER_PORT: ${LOGS_DRIVER_PORT}
      MS_ENDPOINT: ${MS_ENDPOINT}
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    networks:
      fonos:
        aliases:
          - ${APISERVER_ENDPOINT}
    secrets:
      - source: jwt-salt
        target: /home/fonos/.fonos/jwt.salt
      - source: config
        target: /home/fonos/.fonos/config

  datasource:
    extends:
      file: common.yml
      service: common 
    image: ${DS_IMAGE}
    deploy:
      placement:
        constraints: [node.role == manager]    
    command: ['redis-server', '/etc/redis/redis.conf' ]
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource
    networks:
      fonos:
        aliases: 
          - ${DS_HOST}
    configs:
      - source: redis-conf
        target: /etc/redis/redis.conf
    volumes: 
      - datasource:/data

  eventsbroker:
    extends:
      file: common.yml
      service: common 
    image: ${EB_IMAGE}
    environment:
      RABBITMQ_USERNAME: ${EB_USERNAME}
      RABBITMQ_PASSWORD: ${EB_SECRET}
      RABBITMQ_NODE_PORT_NUMBER: ${EB_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.eventsbroker
    networks:
      fonos:
        aliases: 
          - ${EB_HOST}
