# The following services are mandatories for a Fonos deployment

services:

  apiserver:
    extends:
      file: common.yml
      service: common 
    image: ${AS_IMAGE}
    environment:
      ALLOW_INSECURE: 'true'
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
      FS_HOST: ${FS_HOST}
      FS_PORT: ${FS_PORT}
      FS_USERNAME: ${FS_USERNAME}
      FS_SECRET: ${FS_SECRET}
      FS_DEFAULT_STORAGE_BUCKET: ${FS_DEFAULT_STORAGE_BUCKET}
      EVENTS_BROKERS: amqp://${EB_USERNAME}:${EB_SECRET}@${EB_HOST}:${EB_PORT}  
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    networks:
      fonos:
        aliases:
          - apiserver.fonos
    volumes:
      - config:/home/fonos/.fonos:cached

  datasource:
    extends:
      file: common.yml
      service: common 
    image: ${DS_IMAGE}
    command: ['redis-server', '--appendonly', 'yes' ]
    expose:
      - ${DS_PORT}
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource
    networks:
      fonos:
        aliases: 
          - ${DS_HOST}
    volumes: 
      - datasource:/data:cached

  eventsbroker:
    extends:
      file: common.yml
      service: common 
    image: ${EB_IMAGE}
    environment:
      RABBITMQ_USERNAME: ${EB_USERNAME}
      RABBITMQ_PASSWORD: ${EB_SECRET}
      RABBITMQ_NODE_PORT_NUMBER: ${EB_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.eventsbroker      
    networks:
      fonos:
        aliases: 
          - ${EB_HOST}

  fs:
    extends:
      file: common.yml
      service: common    
    image: ${FS_IMAGE}
    volumes:
      - data1-1:/fonos
    expose:
      - ${FS_PORT}
    environment:
      MINIO_ACCESS_KEY: ${FS_USERNAME}
      MINIO_SECRET_KEY: ${FS_SECRET}
    command: minio server /fonos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.fs
    networks:
      fonos:
        aliases: 
          - ${FS_HOST}