# The Session Border Controller or SBC, is a network component sitting at the
# edge to protect the SIP services and assist with connectivity and QoS.

services:

  sipproxy:
    extends:
      file: common.yml
      service: common 
    image: ${SIPPROXY_IMAGE}
    environment:
      EXTERN_ADDR: ${HOST_ADDR}
      DATA_SOURCE_PROVIDER: redis_data_provider
      DATA_SOURCE_PARAMETERS: host=${DS_HOST},port=${DS_PORT}
    ports:
      - ${SIPPROXY_SIP_PORT}:${SIPPROXY_SIP_PORT}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${SIPPROXY_API_PORT} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 1
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    deploy:
      placement:
        constraints:
          - node.labels.topic == sip
    networks:
      fonos:
        aliases:
          - ${SIPPROXY_HOST}

  provisioner:
    image: fonoster/routr-ctl
    entrypoint: |
      sh -c '
        while ! nc -z ${SIPPROXY_HOST} ${SIPPROXY_API_PORT}; do sleep 1; done
        rctl login https://${SIPPROXY_HOST}:${SIPPROXY_API_PORT}/api/v1beta1 \
          -u ${SIPPROXY_API_USERNAME} -p ${SIPPROXY_API_SECRET}
        rctl create -f /bootstrap.yml
      '
    deploy:
      restart_policy: 
        condition: none      
    volumes:
      - ./bootstrap.yml:/bootstrap.yml:ro
    networks:
      fonos:
 