version: '3.7'

services:

  sipproxy:
    image: ${SIPPROXY_IMAGE}
    restart: ${RESTART_POLICY}
    environment:
      EXTERN_ADDR: ${HOST_ADDR}
      DATA_SOURCE_PROVIDER: redis_data_provider
      DATA_SOURCE_PARAMETERS: host=${DS_HOST},port=${DS_PORT},secret=${DS_SECRET}
      BIND_ADDR: 0.0.0.0
      RECORD_ROUTE: 'true'
      REGISTRAR_INTF: Internal
    ports:
      - ${SIPPROXY_SIP_PORT}:${SIPPROXY_SIP_PORT}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${SIPPROXY_API_PORT} || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    networks:
      fonos:
        aliases:
          - ${SIPPROXY_HOST}
    volumes:
      - ${CONFIG}/log4j2.yml:/opt/routr/config/log4j2.yml

  mediaserver:
    image: ${MS_IMAGE}
    restart: ${RESTART_POLICY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediaserver.entrypoints=websecure"
      - "traefik.http.routers.mediaserver.rule=Path(`/ari/asterisk/ping`)"
      - "traefik.http.routers.mediaserver.middlewares=basic-auth@docker"
      - "traefik.http.middlewares.basic-auth.headers.customrequestheaders.Authorization=Basic ${MS_ARI_AUTHORIZATION}"
    expose:
      - 8088
    environment:
      ARI_EXTERNAL_URL: ${MS_ARI_EXTERNAL_URL}
      ARI_USERNAME: ${MS_ARI_USERNAME}
      ARI_SECRET: ${MS_ARI_SECRET}
      EXTERN_ADDR: ${HOST_ADDR}
      EXTERN_PORT: ${MS_SIP_PORT}
      SIPPROXY_HOST: ${HOST_ADDR}:${SIPPROXY_SIP_PORT}
      SIPPROXY_USERNAME: ${SIPPROXY_USERNAME}
      SIPPROXY_SECRET: ${SIPPROXY_SECRET}
      # Give asterisk a fake localnet to force it to always advertise its public address
      LOCALNET: '8.8.8.8'
    volumes:
      - data1-1:/home/fonos
      - ${CONFIG}/config:/home/fonos/.fonos/config
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.mediaserver
    networks:
      fonos:
