# The following services are mandatories for a Fonos deployment

services:

  apiserver:
    extends:
      file: common.yml
      service: common 
    image: ${AS_IMAGE}
    entrypoint: |
      sh -c '
        while [ ! -f ~/.fonos/config ]; do echo 'wating-for-config'; sleep .5; done
        sleep 5
        run-apiserver
      '
    environment:
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    networks:
      fonos:
        aliases:
          - apiserver.fonos
    volumes:
      - config:/root/.fonos:cached

  datasource:
    extends:
      file: common.yml
      service: common 
    image: ${DS_IMAGE}
    command: ['redis-server', '--appendonly', 'yes' ]
    expose:
      - ${DS_PORT}
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource
    networks:
      fonos:
        aliases: ['datasource.fonos']
    volumes: 
      - datasource:/data:cached
