# The default TTS in Fonos is implemented with MaryTTS. It can be replaced 
# with other engine, such as Google Text to Speech. This is an optional component.

services:

  tts:
    extends:
      file: common.yml
      service: common   
    image: ${TTS_IMAGE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TTS_ENGINE_PORT}"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - ${TTS_ENGINE_PORT}:${TTS_ENGINE_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.tts
