version: '3.7'

services:

  tts:
    image: ${TTS_IMAGE}
    restart: ${RESTART_POLICY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TTS_ENGINE_PORT}"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - ${TTS_ENGINE_PORT}:${TTS_ENGINE_PORT}
    networks:
      fonos:
        aliases: 
          - ${TTS_ENGINE_HOST}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.tts

  # EFK services are optional but recommended for state visualization
  logsdriver:
    image: ${LOGS_DRIVER_IMAGE}
    restart: ${RESTART_POLICY}
    ports:
      - ${LOGS_DRIVER_PORT}:${LOGS_DRIVER_PORT}
    volumes:
      - ${CONFIG}/fluent.conf:/fluentd/etc/fluent.conf
    networks:
      fonos:
        aliases: 
          - ${LOGS_DRIVER_HOST}      

  logsaggregator:
    image: ${LOGS_AGGREGATOR_IMAGE}
    restart: ${RESTART_POLICY}
    environment:
      - discovery.type=single-node
    networks: 
      - fonos

  logsmonitor:
    image: ${LOGS_MONITOR_IMAGE}
    restart: ${RESTART_POLICY}
    environment:
      ELASTICSEARCH_HOSTS: http://logsaggregator:${LOGS_AGGREGRATOR_PORT}
    ports:
      - ${LOGS_MONITOR_PORT}:${LOGS_MONITOR_PORT}
    networks: 
      - fonos
