# Asterisk base Media Sever

services:

  mediaserver:
    extends:
      file: common.yml
      service: common
    image: ${MS_IMAGE}
    environment:
      EXTERN_ADDR: ${HOST_ADDR}
      EXTERN_PORT: ${MS_SIP_PORT}
      # Warning: Temporal value
      AGI_URL: agi://${MC_HOST_PUBLIC}:${MC_AGI_PORT}
      SIPPROXY_HOST: ${SIPPROXY_HOST_PUBLIC}
      SIPPROXY_USERNAME: ${SIPPROXY_USERNAME}
      SIPPROXY_SECRET: ${SIPPROXY_SECRET}
      # Give asterisk a fake localnet to force it to always advertise its public address
      LOCALNET: '8.8.8.8'
    volumes:
      - recordings:/home/fonos/recordings
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.mediaserver
    deploy:
      placement:
        constraints:
          - node.labels.topic == sip
    networks:
      host_mode:
