# Asterisk base Media Sever

services:

  mediaserver:
    extends:
      file: common.yml
      service: common
    image: ${MS_IMAGE}
    environment:
      EXTERN_ADDR: ${HOST_ADDR}
      AGI_URL: agi://${MC_HOST}
      SIPPROXY_HOST: ${SIPPROXY_HOST}
      SIPPROXY_USERNAME: ${SIPPROXY_USERNAME}
      SIPPROXY_SECRET: ${SIPPROXY_SECRET}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.mediaserver
    networks:
      fonos:
        aliases:
          - ${MS_HOST}