# Optional configuration for development environments

services:

  logsdriver:
    ports:
      - ${LOGS_DRIVER_PORT}:${LOGS_DRIVER_PORT}
  apiserver:
    environment:
      ALLOW_INSECURE: 'true'
  datasource:
    ports:
    - ${DS_PORT}:${DS_PORT}
  eventsbroker:
    ports:
    - ${EB_PORT}:${EB_PORT}
  sipproxy:
    ports:
    - ${SIPPROXY_API_PORT}:${SIPPROXY_API_PORT}
    - ${SIPPROXY_SIP_PORT}:${SIPPROXY_SIP_PORT}
  tts:
    ports:
    - ${TTS_ENGINE_PORT}:${TTS_ENGINE_PORT}
  mediaserver:
    environment:
      ENABLE_TEST_ACCOUNT: 'true'
    ports:
      - ${MS_SIP_PORT}:${MS_SIP_PORT}
      - ${MS_RTP_PORT_START}-${MS_RTP_PORT_END}:${MS_RTP_PORT_START}-${MS_RTP_PORT_END}/udp