# Warning: Including this file in your Fonos deployment will
# open the ports to a number of private services. This is very
# unsecured. Only recommended for development.

version: '3.7'

services:

  apiserver:
    ports:
      - 8080:8080
      - 50051:50051
  datasource:
    ports:
      - ${DS_PORT}:${DS_PORT}
  fs:
    ports:
      - ${FS_PORT}:${FS_PORT}
  sipproxy:
    ports:
      - ${SIPPROXY_API_PORT}:${SIPPROXY_API_PORT}
  mediaserver:
    ports:
      - 6060:6060
      - 20000-20020:20000-20020/udp
    environment:
      ENABLE_TEST_ACCOUNT: "true"
      RTP_PORT_START: 20000
      RTP_PORT_END: 20020
