version: '3.7'

services:

  secrets:
    ports:
      - "8200:8200"
  reverse_proxy:
    ports:
      - 8080:8080
  datasource:
    ports:
      - ${DS_PORT}:${DS_PORT}
  datasource_auth:
    ports:
      - 27017:27017
  eventsbroker:
    ports:
      - ${EB_PORT}:${EB_PORT}
  fs:
    ports:
      - ${FS_PORT}:${FS_PORT}
  sipproxy:
    ports:
      - ${SIPPROXY_API_PORT}:${SIPPROXY_API_PORT}
  mediacontroller:
    ports:
      - ${MC_AGI_PORT}:${MC_AGI_PORT}
  mediaserver:
    environment:
      ENABLE_TEST_ACCOUNT: "true"