# The following services are mandatories for a Fonos deployment

services:

  fs:
    deploy:
      restart_policy: 
        condition: on-failure
    image: ${FS_IMAGE}
    volumes:
      - data1-1:/fonos
    environment:
      MINIO_ACCESS_KEY: ${FS_USERNAME}
      MINIO_SECRET_KEY: ${FS_SECRET}
    command: minio server /fonos
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.fs
    networks:
      fonos:
        aliases: 
          - ${FS_HOST}

networks:
  fonos:
volumes:
  data1-1:
    external: true
