version: '3.7'

services:

  provisioner:
    image: fonoster/routr-ctl
    entrypoint: >
      /bin/sh -c "
      set -e;
      rctl login https://${SIPPROXY_HOST}:${SIPPROXY_API_PORT}/api/v1beta1 -u ${SIPPROXY_API_USERNAME} -p ${SIPPROXY_API_SECRET};
      rctl create -f /bootstrap.yml;
      exit 0;
      "
    networks:
      fonos:
    volume:
      - ${CONFIG}/bootstrap.yml:/bootstrap.yml