apiVersion: v1alpha1
metadata:
  realm: fonoster.com
specs:
  common-access:
    username: admin
    secret: changeit
  services:
    apiServer:
      port: 3001
      salt: djghhhhuuwiwuewieuwieuriwu
    fileserver.host: fileserver
    mediaServer.host: mediaserver
    mediaController.host: mediacontroller
    messageBus.host: messagebus
    datasource.host: datasource
