# NOTICE: This is here for testing convinience You should not use this
# in production as it has many unneeded open ports and the display of
# credentials.

version: '3.7'
services:

  provisioner:
    env_file: .env
    build:
      context: .rctl
    entrypoint: |
      sh -c '
        while ! nc -z $SIPPROXY_HOST ${SIPPROXY_API_PORT}; do sleep 0.1; done
        rctl login https://${SIPPROXY_HOST}:${SIPPROXY_API_PORT}/api/v1beta1 \
          -u ${SIPPROXY_API_USERNAME} -p ${SIPPROXY_API_SECRET}
        rctl create -f /etc/bootstrap.yml
      '
    volumes:
      - ./etc/bootstrap.yml:/etc/bootstrap.yml:ro

  apiserver:
    depends_on: [certs]
    logging:
      driver: json-file
    volumes:
      - credentials:/root/.fonos
      - certs:/certs:ro
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}

  sipproxy:
    logging:
      driver: json-file
    volumes:
      - ./etc/log4j2.yml:/opt/routr/config/log4j2.yml
    ports:
      - ${SIPPROXY_SIP_PORT}:${SIPPROXY_SIP_PORT}
      - ${SIPPROXY_API_PORT}:${SIPPROXY_API_PORT}

  mediaserver:
    logging:
      driver: json-file
    environment:
      ENABLE_TEST_ACCOUNT: 'true'
    ports:
      - ${MS_SIP_PORT}:${MS_SIP_PORT}

  mediacontroller:
    depends_on: [certs]
    logging:
      driver: json-file
    volumes:
      - credentials:/root/.fonos:ro
      - certs:/certs

  datasource:
    logging:
      driver: json-file
    volumes:
      - datasource:/data
    ports:
      - ${DS_PORT}:${DS_PORT}

  fs:
    logging:
      driver: json-file
    ports:
      - ${FS_PORT}:${FS_PORT}

  tts:
    logging:
      driver: json-file
    ports:
      - ${TTS_ENGINE_PORT}:${TTS_ENGINE_PORT}

  integrationtests:
    env_file: .env
    image: integrationtests
    build:
      context: mods
      dockerfile: Dockerfile.mc
    environment:
      FONOS_ENDPOINT: ${APISERVER_ENDPOINT}
    entrypoint: |
      sh -c '
        #while [ ! -f /root/.fonos/access ]; do sleep 2; done
        npm i nyc mocha -g
        cd /mods
        npm test
      '
    volumes:
      - credentials:/root/.fonos:ro

  certs:
    image: fonoster/certshelper
    entrypoint: |
      sh -c '
        cp /ca/* /certs
        gen-certs
      '    
    environment:
      CERT_NAME: server
      SUBJECT: apiserver
    volumes:
      - certs:/certs
      - ./etc/certs:/ca
volumes:
  data1-1:
  datasource:
  credentials:
  certs:
