version: '3.2'
services:
  sipproxy:
    depends_on: [redis]
    image: fonoster/routr:latest
    entrypoint: |
      sh -c '
        while ! nc -z redis 6379; do sleep 0.1; done # Wait for Redis
        ./run.sh &
        while ! nc -z localhost 4567; do sleep 0.1; done # Wait for Routr
        ./rctl create -f bootstrap.yml
        while sleep 3600; do :; done
      '
    environment:
      ROUTR_EXTERN_ADDR: ${HOST_ADDR}
      ROUTR_DS_PROVIDER: redis_data_provider
      ROUTR_DS_PARAMETERS: "host=redis,port=6379"
    ports:
      - 4567:4567
      - 5060:5060
    volumes:
      - ./etc/bootstrap.yml:/opt/routr/bootstrap.yml:ro
  mediaserver:
    environment:
      CASTK_EXTERN_ADDR: ${HOST_ADDR}
      CASTK_SIPPROXY_HOST: ${HOST_ADDR}
      CASTK_SIPPROXY_USERNAME: ast
      CASTK_SIPPROXY_SECRET: changeit
      CASTK_ARI_APP: hello-world
    image: fonoster/castk
    ports:
      - 6060:6060
      - 8088:8088
  mediacontroller:
    image: node
    entrypoint: |
      sh -c '
        sleep 5
        cd /opt/apps/hello-world/ && node --experimental-modules main.mjs
        while sleep 3600; do :; done
      '
    volumes:
      - ./apps:/opt/apps:ro
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
