version: '3.2'
services:
  sipproxy:
    depends_on: [redis]
    image: fonoster/sipio:latest
    entrypoint: |
      sh -c '
          while ! nc -z redis 6379; do sleep 0.1; done # Wait for Redis
          ./run.sh &
          while ! nc -z localhost 4567; do sleep 0.1; done # Wait for Sip I/O
          ./sipioctl create -f bootstrap.yml
          while sleep 3600; do :; done
      '
    environment:
      SIPIO_EXTERN_ADDR: ${EXTERN_ADDR}
      SIPIO_DS_PROVIDER: redis_data_provider
      SIPIO_DS_PARAMETERS: "host=redis,port=6379"
    ports:
      - 4567:4567
      - 5060:5060
    volumes:
      - ./etc/bootstrap.yml:/opt/sipio/bootstrap.yml:ro
  mediaserver:
    environment:
      ASTERISK_EXTERN_ADDR: ${HOST_ADDR}
      ASTERISK_SIPPROXY_HOST: ${HOST_ADDR}
      ASTERISK_SIPPROXY_USERNAME: ast
      ASTERISK_SIPPROXY_SECRET: changeit
      ASTERISK_FASTAGI_URL: agi://mediacontroller/examples/HelloWorld
      ASTERISK_MANAGER_SECRET: changeit
    image: fonoster/fast
    ports:
      - 6060:6060
  mediacontroller:
    image: fonoster/astive
    ports:
      - 4573:4573
    volumes:
      - ./apps:/opt/astive/apps:ro
      - ./etc/astived.properties:/opt/astive/conf/astived.properties:ro
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
