apiVersion: v1
kind: Service
metadata:
  name: mediaserver
  labels:
    app: yaps
spec:
  ports:
  - name: sip
    port: 6060
  - name: ami
    port: 5038
  selector:
    app: yaps
    tier: media
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mediaserver
  labels:
    app: yaps
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yaps
        tier: media
    spec:
      containers:
      - name: mediaserver
        image: fonoster/castk
        imagePullPolicy: Always
        env:
        - name: CASTK_EXTERN_ADDR
          value: 192.168.1.2
        - name: CASTK_SIPPROXY_HOST
          value: 192.168.1.2
        - name: CASTK_SIPPROXY_USERNAME
          value: ast
        - name: CASTK_SIPPROXY_SECRET
          value: changeit
        - name: CASTK_ARI_APP
          value: hello-world
        ports:
        - containerPort: 5038
          name: ami
        - containerPort: 6060
          name: sip
