apiVersion: v1
kind: Service
metadata:
  name: sipproxy
  labels:
    app: yaps
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # This will cause the load balancer to send the client ip
  ports:
  - name: sip
    port: 5060
  - name: https
    port: 4567
  selector:
    app: yaps
    tier: signaling
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sipproxy
  labels:
    app: yaps
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yaps
        tier: signaling
    spec:
      containers:
      - name: sipproxy
        image: fonoster/routr
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sh /opt/routr/entrypoint.sh"]
        env:
        - name: ROUTR_DS_PROVIDER
          value: redis_data_provider
        - name: ROUTR_DS_PARAMETERS
          value: 'host=redis,port=6379'
        - name: ROUTR_EXTERN_ADDR
          value: '192.168.1.127'
        ports:
         - containerPort: 5060
           name: sip
         - containerPort: 4567
           name: https
        volumeMounts:
          - name: entrypoint
            mountPath: /opt/routr/entrypoint.sh
            subPath: entrypoint.sh
          - name: bootstrap
            mountPath: /opt/routr/bootstrap.yml
            subPath: bootstrap.yml
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint
      - name: bootstrap
        configMap:
          name: bootstrap
