apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}-apiserver
  labels:
    app: apiserver
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: apiserver
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-{{ include ".helm2.fullname" . }}-minio
        image: busybox
        command: ['sh', '-c', 'until nslookup {{ include ".helm2.fullname" . }}-minio; do echo waiting for {{ include ".helm2.fullname" . }}-minio; sleep 2; done;']
      - name: create-default-buckets
        image: fonoster/fonos-apiserver:latest
        command:
        - node
        - node_modules/@fonos/core/dist/common/fsutils.js
        envFrom:
          - configMapRef:
              name: {{ include ".helm2.fullname" . }}-env              
      containers:       
      - name: fonos
        image: fonoster/fonos-apiserver:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /root/.fonos
          name: fonos-access
          readOnly: true
        ports:
        - name: grpc
          containerPort: 50052
        envFrom:
        - configMapRef:
            name: {{ include ".helm2.fullname" . }}-env   
      volumes:
      - name: fonos-access
        secret:
          secretName: fonos-access
