apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}-mediacontroller
  labels:
    app: mediacontroller
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: mediacontroller
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      #  fsGroup: 1000
      #initContainers:
      #  - name: take-data-dir-ownership
      #    image: alpine:3.6
      #    # Give `mediacontroller` user (id 472) permissions a mounted volume
      #    command:
      #    - chown
      #    - -R  
      #    - 472:472
      #    - /fonos/apps
      #    volumeMounts:
      #    - mountPath: /fonos
      #      name: shared-files
      #      readOnly: false  
      containers:
      - name: mediacontroller
        image: fonoster/fonos-nodejsmc:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /root/.fonos
            name: fonos-access
            readOnly: true
          - mountPath: /fonos
            name: shared-files
            readOnly: false
        ports:
        - name: agi
          containerPort: 4573
        envFrom:
        - configMapRef:
            name: {{ include ".helm2.fullname" . }}-env     
      volumes:
        - name: fonos-access
          secret:
            secretName: fonos-access
        - name: shared-files
          persistentVolumeClaim:
            claimName: {{ include ".helm2.fullname" . }}-minio