apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}-sipproxy
  labels:
    app: sipproxy
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: sipproxy
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      #initContainers:
      #- name: netdiscover
      #  image: cycoresystems/netdiscover:latest    
      containers:
      - name: sipproxy
        image: fonoster/routr:latest
        imagePullPolicy: Always
        env:
        - name: REGISTRAR_INTF
          value: Internal
        - name: EXTERN_ADDR
          value: {{ .Values.sipproxy.externAddr | quote }}
        - name: DATA_SOURCE_PROVIDER
          value: redis_data_provider
        - name: DATA_SOURCE_PARAMETERS
          value: host={{ include ".helm2.fullname" . }}-redis-master,port=6379
        ports:
        - name: sig
          containerPort: 5060
        - name: api
          containerPort: 4567
