apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}-sipproxy
  labels:
    app: sipproxy
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.sipproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}  
spec:
  replicas: {{ .Values.sipproxy.replicaCount }}
  strategy:
    type: {{ .Values.sipproxy.strategyType | quote }}
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.sipproxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: sipproxy
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: sipproxy
        image: {{ .Values.sipproxy.image.repository }}:{{ .Values.sipproxy.image.tag }}
        imagePullPolicy: {{ .Values.sipproxy.image.pullPolicy }}
        env:
        - name: REGISTRAR_INTF
          value: Internal
        - name: EXTERN_ADDR
          value: {{ .Values.sipproxy.externAddr | quote }}
        - name: DATA_SOURCE_PROVIDER
          value: redis_data_provider
        - name: DATA_SOURCE_PARAMETERS
          value: host={{ printf "%s-%s" .Release.Name .Values.redis.nameOverride }}-master,port=6379
        ports:
        - name: tcp
          containerPort: 5060
        - name: udp
          containerPort: 5061
          protocol: UDP
        - name: tls
          containerPort: 5062
        - name: ws
          containerPort: 5063 
        - name: wss
          containerPort: 5064             
        - name: https
          containerPort: 4567
