apiVersion: v1
kind: Service
metadata:
  #name:  {{ include ".helm2.fullname" . }}-apiserver
  name: apiserver
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
  selector:
    {{- include ".helm2.selectorLabels" . | nindent 4 }}