apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm2.fullname" . }}-apiserver
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  sessionAffinity: None
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
  selector:
    {{- include ".helm2.selectorLabels" . | nindent 4 }}