apiVersion: v1
kind: Service
metadata:
  name:  {{ include ".helm2.fullname" . }}-mediaserver
  labels:
    app: mediaserver
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.mediaserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}    
spec:
  type: {{ .Values.mediaserver.service.type }}
  ports:
  - name: sip
    port: {{ .Values.mediaserver.service.port }}
    targetPort: {{ .Values.mediaserver.port  }}
  # Experimental ports
  - name: rtp1
    port: 30005
    targetPort: 30005
    protocol: UDP
  - name: rtp2
    port: 30006
    targetPort: 30006
    protocol: UDP
  - name: rtp3
    port: 30007
    targetPort: 30007 
    protocol: UDP
  - name: rtp4
    port: 30008
    targetPort: 30008
    protocol: UDP    
  selector:
    app: mediaserver
    {{- include ".helm2.selectorLabels" . | nindent 4 }}