apiVersion: v1
kind: Service
metadata:
  name:  {{ include ".helm2.fullname" . }}-mediaserver
  labels:
    app: mediaserver
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.mediaserver.serviceType }}
  externalTrafficPolicy: Local
  ports:
  - name: sip
    port: {{ .Values.mediaserver.port }}
    targetPort: {{ .Values.mediaserver.port  }}
    {{- if eq .Values.mediaserver.serviceType "NodePort" }}
    nodePort: {{ .Values.mediaserver.externPort }}
    {{- end }}
  - name: rtp1
    port: 30005
    targetPort: 30005
    nodePort: 30005
    protocol: UDP
  - name: rtp2
    port: 30006
    targetPort: 30006
    nodePort: 30006
    protocol: UDP
  - name: rtp3
    port: 30007
    targetPort: 30007 
    nodePort: 30007
    protocol: UDP
  - name: rtp4
    port: 30008
    targetPort: 30008
    nodePort: 30008
    protocol: UDP    
  selector:
    app: mediaserver
    {{- include ".helm2.selectorLabels" . | nindent 4 }}