apiVersion: v1
kind: Service
metadata:
  name:  {{ include ".helm2.fullname" . }}-mediaserver
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: sip
    port: 6060
    targetPort: 6060
  selector:
    {{- include ".helm2.selectorLabels" . | nindent 4 }}