apiVersion: v1
kind: Service
metadata:
  name:  {{ include ".helm2.fullname" . }}-ttsengine
  labels:
    app: ttsengine
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 59125
    targetPort: 59125
  selector:
    app: ttsengine
    {{- include ".helm2.selectorLabels" . | nindent 4 }}