# Optional Funcs API service

version: '3.7'

networks:
  fonos:

services:

  funcs_api:
    image: fonoster/fonos-funcs
    environment:
      FUNCS_WORKDIR: ${FUNCS_WORKDIR}
      FUNCS_URL: ${FUNCS_URL}
      FUNCS_USERNAME: ${FUNCS_USERNAME}
      FUNCS_SECRET: ${FUNCS_SECRET}
      DOCKER_REGISTRY_ORG: ${DOCKER_REGISTRY_ORG}
      DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
      DOCKER_REGISTRY_SECRET: ${DOCKER_REGISTRY_SECRET}
      DOCKER_REGISTRY: ${DOCKER_REGISTRY}
      DOCKER_REGISTRY_SERVICE: ${DOCKER_REGISTRY_SERVICE}
      DOCKER_REGISTRY_AUTH_ENDPOINT: ${DOCKER_REGISTRY_AUTH_ENDPOINT}
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.funcs_api.entrypoints=internal,websecure"
      - "traefik.http.routers.funcs_api.rule=PathPrefix(`/fonos.funcs.v1alpha1`)"
      - "traefik.http.services.funcs_api.loadbalancer.server.scheme=h2c"
    volumes:
      - data1-1:/home/fonos
      - /var/run/docker.sock:/var/run/docker.sock