# Optional Logging services (Elastic Search, Kibana, Fluent)

version: '3.7'

networks:
  fonoster:

services:

  logsdriver:
    image: fonoster/fluent-elasticsearch:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    ports:
      - ${LOGS_DRIVER_PORT}:${LOGS_DRIVER_PORT}
    volumes:
      - ${CONFIG}/fluent.conf:/fluentd/etc/fluent.conf:ro
    networks:
      fonoster:
        aliases: 
          - ${LOGS_DRIVER_HOST}      

  logsaggregator:
    image: fonoster/elasticsearch:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - discovery.type=single-node
    networks: 
      - fonos

  logsmonitor:
    image: fonoster/kibana:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      ELASTICSEARCH_HOSTS: http://logsaggregator:${LOGS_AGGREGRATOR_PORT}
    ports:
      - ${LOGS_MONITOR_PORT}:${LOGS_MONITOR_PORT}
    networks: 
      - fonos
