# Vault Initialization script

version: '3.7'

networks:
  fonos:

services:

  secrets_init:
    image: fonoster/fonos-secrets:${COMPOSE_PROJECT_VERSION}
    entrypoint: /bin/sh -c "init"
    networks:
      fonos:
