# Optional Tracing monitor service (Jaeger)

version: '3'

networks:
  fonoster:

services:
  jaeger:
    image: jaegertracing/all-in-one:1.30.0
    ports:
      - 16686:16686
      - 14268:14268
      - 14250
    networks:
      fonoster: