# Optional Tracing monitor service (Jaeger)

version: '3'

networks:
  fonoster:

services:
  jaeger:
    image: jaegertracing/all-in-one:1.30.0
    ports:
      - 14268:14268
      - 14250
    expose:
      - 16686
    labels:
      - traefik.enable=true
      - traefik.http.routers.jaeger.entrypoints=internal,websecure
      - traefik.http.routers.jaeger.rule=PathPrefix(`/search`, `/trace`, `/dependencies`, `/static`, `/api/services`, `/api/traces`, `/api/dependencies`)
      - traefik.http.routers.jaeger.service=jaeger
      - traefik.http.services.jaeger.loadbalancer.server.port=16686
      - traefik.http.middlewares.jaeger-auth.basicauth.users=${JAEGER_USERNAME}:${JAEGER_PASSWORD_HASH}
      - traefik.http.middlewares.jaeger-chain.chain.middlewares=jaeger-auth
      - traefik.http.routers.jaeger.middlewares=jaeger-chain
    networks:
      fonoster: