version: '3.7'

networks:
  fonoster:

services:
  voice:
    restart: ${RESTART_POLICY}
    image: fonoster/voice:${COMPOSE_PROJECT_VERSION}
    command: ['rox']
    ports:
      - 3000:3000
      - 3001:3001
      - 9090:9090
    environment:
      - DEFAULT_LANGUAGE_CODE
      - OTL_EXPORTER_ZIPKIN_URL
      - OTL_EXPORTER_JAEGER_URL
      - OTL_EXPORTER_PROMETHEUS_PORT
      - OTL_EXPORTER_GCP_ENABLED
      - GOOGLE_CONFIG_FILE
      - LOGS_LEVEL     
    volumes:
      - ${CONFIG}/google.json:/home/fonoster/.fonoster/google.json
    networks:
      fonoster:
        aliases: 
          - ${VOICE_HOST}
