name: Publish to GH Pages
on:
  push:
    paths:
    - 'docs/**'
    branches:
    - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Copy docs to Wiki
      uses: docker://decathlon/wiki-page-creator-action:2.0.1
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: docs
        ACTION_MAIL: fonosterteam@fonoster.com
        ACTION_NAME: psanders
        OWNER: fonoster
        REPO_NAME: yaps
