name: release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(node -e "console.log(require('./lerna.json').version)")
    - run: |
        npm config set unsafe-perm true
        npm install lerna -g
        npm install
        npm run bootstrap
        npm run build
    - name: Publish Agents API at Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fonoster/fonos-agents
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        workdir: mods/agents
        tags: "latest, ${{ steps.get_version.outputs.VERSION }}"        
    - name: Publishing Media Controller Service
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: publish to docker hub
        repo: fonoster/fonos-nodejsmc
        token: ${{ secrets.GH_PAT }}
        ref: master
        inputs: '{"version": "${{ steps.get_version.outputs.VERSION }}" }'
    - name: Publishing Uploader Helper Service
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: publish to docker hub
        repo: fonoster/uploaderhelper
        token: ${{ secrets.GH_PAT }}
        ref: master
        inputs: '{"version": "${{ steps.get_version.outputs.VERSION }}" }'
    - name: Publishing Config Helper Service
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: publish to docker hub
        repo: fonoster/confighelper
        token: ${{ secrets.GH_PAT }}
        ref: main
        inputs: '{"version": "${{ steps.get_version.outputs.VERSION }}" }'
    - name: Publishing Chmod Helper Service
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: publish to docker hub
        repo: fonoster/chmodhelper
        token: ${{ secrets.GH_PAT }}
        ref: master
        inputs: '{"version": "${{ steps.get_version.outputs.VERSION }}" }'
    - name: Publishing JWTHelper Service
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: publish to docker hub
        repo: fonoster/jwthelper
        token: ${{ secrets.GH_PAT }}
        ref: master
        inputs: '{"version": "${{ steps.get_version.outputs.VERSION }}" }'
