name: unit tests
on:
  push:
    paths:
    - 'mods/**'
    branches:
    - master
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare environment
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Running tests
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: |
          npm config set unsafe-perm true
          npm install lerna -g
          npm install
          npm run bootstrap
          npm run build
          npm test
      - name: Running SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
